# Generated by Django 5.2.4 on 2025-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='nombre',
            field=models.CharField(default='Algo', max_length=50),
        ),
    ]
